/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Carlos Enrique
 */
public class JPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JPrincipal
     */
    public JPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        barUsuario = new javax.swing.JMenu();
        itmControlUsuario = new javax.swing.JMenuItem();
        barPersonal = new javax.swing.JMenu();
        itemControlPersonal = new javax.swing.JMenuItem();
        itemControlCargo = new javax.swing.JMenuItem();
        itemControlAsistencia = new javax.swing.JMenuItem();
        itemControlAusencia = new javax.swing.JMenuItem();
        itemControlTipoAusencia = new javax.swing.JMenuItem();
        barInsumo = new javax.swing.JMenu();
        itemControlInsumo = new javax.swing.JMenuItem();
        itemControlTipoInsumo = new javax.swing.JMenuItem();
        itemControlAlmacen = new javax.swing.JMenuItem();
        barServicio = new javax.swing.JMenu();
        itemControlServicio = new javax.swing.JMenuItem();
        itemControlTipoServicio = new javax.swing.JMenuItem();
        barOrganizacion = new javax.swing.JMenu();
        itemControlOrganizacion = new javax.swing.JMenuItem();
        itemControlTipoOrg = new javax.swing.JMenuItem();
        itemEvaluacion = new javax.swing.JMenuItem();
        barPlanificacion = new javax.swing.JMenu();
        itemPlanificacionServicio = new javax.swing.JMenuItem();
        BarConsultas = new javax.swing.JMenu();
        itemConsultarPersonal = new javax.swing.JMenuItem();
        itemConsultarOrganizacion = new javax.swing.JMenuItem();
        itemConsultarTipoInsumo = new javax.swing.JMenuItem();
        itemConsultarTipoServicio = new javax.swing.JMenuItem();
        itemConsultarTipoOrg = new javax.swing.JMenuItem();
        itemConsultarCargos = new javax.swing.JMenuItem();
        itemConsultarAlmacen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("BIENVENIDOS AL  SISTEMA ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("EMPRESA DE VIGILANCIA ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("LA UNION 2010 S.A");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOLAUNION.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(5, 5, 5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel3)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        barUsuario.setText("Usuario");

        itmControlUsuario.setText("Control de Usuario");
        barUsuario.add(itmControlUsuario);

        jMenuBar1.add(barUsuario);

        barPersonal.setText("Personal");

        itemControlPersonal.setText("Control Personal");
        barPersonal.add(itemControlPersonal);

        itemControlCargo.setText("Control Cargo");
        barPersonal.add(itemControlCargo);

        itemControlAsistencia.setText("Control Asistencia");
        barPersonal.add(itemControlAsistencia);

        itemControlAusencia.setText("Control Ausencia");
        barPersonal.add(itemControlAusencia);

        itemControlTipoAusencia.setText("Control Tipo Ausencia");
        barPersonal.add(itemControlTipoAusencia);

        jMenuBar1.add(barPersonal);

        barInsumo.setText("Insumo");

        itemControlInsumo.setText("Control Insumo");
        barInsumo.add(itemControlInsumo);

        itemControlTipoInsumo.setText("Control Tipo Insumo");
        barInsumo.add(itemControlTipoInsumo);

        itemControlAlmacen.setText("Control Almacen");
        barInsumo.add(itemControlAlmacen);

        jMenuBar1.add(barInsumo);

        barServicio.setText("Servicio");

        itemControlServicio.setText("Control Servicio");
        barServicio.add(itemControlServicio);

        itemControlTipoServicio.setText("Control Tipo Servicio");
        barServicio.add(itemControlTipoServicio);

        jMenuBar1.add(barServicio);

        barOrganizacion.setText("Organizacion");

        itemControlOrganizacion.setText("Control Organizacion");
        barOrganizacion.add(itemControlOrganizacion);

        itemControlTipoOrg.setText("Control Tipo Organizacion");
        barOrganizacion.add(itemControlTipoOrg);

        itemEvaluacion.setText("Evaluacion del Tipo de Organizacion");
        barOrganizacion.add(itemEvaluacion);

        jMenuBar1.add(barOrganizacion);

        barPlanificacion.setText("Planificacion");

        itemPlanificacionServicio.setText("Planificacion de Servicio");
        barPlanificacion.add(itemPlanificacionServicio);

        jMenuBar1.add(barPlanificacion);

        BarConsultas.setText("Consultas");

        itemConsultarPersonal.setText("Consultar Personal");
        BarConsultas.add(itemConsultarPersonal);

        itemConsultarOrganizacion.setText("Consultar Organizacion");
        BarConsultas.add(itemConsultarOrganizacion);

        itemConsultarTipoInsumo.setText("Consultar Tipo de Insumo");
        BarConsultas.add(itemConsultarTipoInsumo);

        itemConsultarTipoServicio.setText("Consultar Tipo de Servicio");
        BarConsultas.add(itemConsultarTipoServicio);

        itemConsultarTipoOrg.setText("Consultar Tipo de Organizacion");
        BarConsultas.add(itemConsultarTipoOrg);

        itemConsultarCargos.setText("Consultar Cargo");
        BarConsultas.add(itemConsultarCargos);

        itemConsultarAlmacen.setText("Consultar Almacen");
        BarConsultas.add(itemConsultarAlmacen);

        jMenuBar1.add(BarConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPrincipal().setVisible(true);
            }
        });
    }

    public JMenu getBarInsumo() {
        return barInsumo;
    }

    public JMenu getBarOrganizacion() {
        return barOrganizacion;
    }

    public JMenu getBarPersonal() {
        return barPersonal;
    }

    public JMenu getBarPlanificacion() {
        return barPlanificacion;
    }

    public JMenu getBarServicio() {
        return barServicio;
    }

    public JMenu getBarUsuario() {
        return barUsuario;
    }

    public JMenuItem getItemControlAlmacen() {
        return itemControlAlmacen;
    }

    public JMenuItem getItemControlAsistencia() {
        return itemControlAsistencia;
    }

    public JMenuItem getItemControlAusencia() {
        return itemControlAusencia;
    }

    public JMenuItem getItemControlCargo() {
        return itemControlCargo;
    }

    public JMenuItem getItemControlInsumo() {
        return itemControlInsumo;
    }

    public JMenuItem getItemControlOrganizacion() {
        return itemControlOrganizacion;
    }

    public JMenuItem getItemControlPersonal() {
        return itemControlPersonal;
    }

    public JMenuItem getItemControlServicio() {
        return itemControlServicio;
    }

    public JMenuItem getItemControlTipoAusencia() {
        return itemControlTipoAusencia;
    }

    public JMenuItem getItemControlTipoInsumo() {
        return itemControlTipoInsumo;
    }

    public JMenuItem getItemControlTipoOrg() {
        return itemControlTipoOrg;
    }

    public JMenuItem getItemControlTipoServicio() {
        return itemControlTipoServicio;
    }

    public JMenuItem getItemEvaluacion() {
        return itemEvaluacion;
    }

    public JMenuItem getItemPlanificacionServicio() {
        return itemPlanificacionServicio;
    }

    public JMenuItem getItmControlUsuario() {
        return itmControlUsuario;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JMenu getBarConsultas() {
        return BarConsultas;
    }

    public JMenuItem getItemConsultarAlmacen() {
        return itemConsultarAlmacen;
    }

    public JMenuItem getItemConsultarCargos() {
        return itemConsultarCargos;
    }

    public JMenuItem getItemConsultarOrganizacion() {
        return itemConsultarOrganizacion;
    }

    public JMenuItem getItemConsultarPersonal() {
        return itemConsultarPersonal;
    }

    public JMenuItem getItemConsultarTipoInsumo() {
        return itemConsultarTipoInsumo;
    }

    public JMenuItem getItemConsultarTipoOrg() {
        return itemConsultarTipoOrg;
    }

    public JMenuItem getItemConsultarTipoServicio() {
        return itemConsultarTipoServicio;
    }

    
    
        public void agregarListener (ActionListener accion)
{
    this.barInsumo.addActionListener(accion);
    this.barOrganizacion.addActionListener(accion);
    this.barPersonal.addActionListener(accion);
    this.barPlanificacion.addActionListener(accion);
    this.barServicio.addActionListener(accion);
    this.barUsuario.addActionListener(accion);
    this.itemControlAlmacen.addActionListener(accion);
    this.itemControlAsistencia.addActionListener(accion);
    this.itemControlAusencia.addActionListener(accion);
    this.itemControlCargo.addActionListener(accion);
    this.itemControlInsumo.addActionListener(accion);
    this.itemControlOrganizacion.addActionListener(accion);
    this.itemControlPersonal.addActionListener(accion);
    this.itemControlServicio.addActionListener(accion);
    this.itemControlTipoAusencia.addActionListener(accion);
    this.itemControlTipoInsumo.addActionListener(accion);
    this.itemControlTipoOrg.addActionListener(accion);
    this.itemEvaluacion.addActionListener(accion);
    this.itemControlTipoServicio.addActionListener(accion);
    this.itmControlUsuario.addActionListener(accion);
    this.itemPlanificacionServicio.addActionListener(accion);
    this.itemConsultarAlmacen.addActionListener(accion);
    this.itemConsultarCargos.addActionListener(accion);
    this.itemConsultarOrganizacion.addActionListener(accion);
    this.itemConsultarTipoOrg.addActionListener(accion);
    this.itemConsultarPersonal.addActionListener(accion);
    this.itemConsultarTipoInsumo.addActionListener(accion);
    this.itemConsultarTipoServicio.addActionListener(accion);
    
    
  
}  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BarConsultas;
    private javax.swing.JMenu barInsumo;
    private javax.swing.JMenu barOrganizacion;
    private javax.swing.JMenu barPersonal;
    private javax.swing.JMenu barPlanificacion;
    private javax.swing.JMenu barServicio;
    private javax.swing.JMenu barUsuario;
    private javax.swing.JMenuItem itemConsultarAlmacen;
    private javax.swing.JMenuItem itemConsultarCargos;
    private javax.swing.JMenuItem itemConsultarOrganizacion;
    private javax.swing.JMenuItem itemConsultarPersonal;
    private javax.swing.JMenuItem itemConsultarTipoInsumo;
    private javax.swing.JMenuItem itemConsultarTipoOrg;
    private javax.swing.JMenuItem itemConsultarTipoServicio;
    private javax.swing.JMenuItem itemControlAlmacen;
    private javax.swing.JMenuItem itemControlAsistencia;
    private javax.swing.JMenuItem itemControlAusencia;
    private javax.swing.JMenuItem itemControlCargo;
    private javax.swing.JMenuItem itemControlInsumo;
    private javax.swing.JMenuItem itemControlOrganizacion;
    private javax.swing.JMenuItem itemControlPersonal;
    private javax.swing.JMenuItem itemControlServicio;
    private javax.swing.JMenuItem itemControlTipoAusencia;
    private javax.swing.JMenuItem itemControlTipoInsumo;
    private javax.swing.JMenuItem itemControlTipoOrg;
    private javax.swing.JMenuItem itemControlTipoServicio;
    private javax.swing.JMenuItem itemEvaluacion;
    private javax.swing.JMenuItem itemPlanificacionServicio;
    private javax.swing.JMenuItem itmControlUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
